---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install wget (CentOS)
    package:
      name: wget
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - ubuntu

- hosts: centos
  become: true
  roles:
    - centos
